spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/****
      username: ****
      password: ****
  main:
    banner-mode: off
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
